# Change this to your website's URL when you publish your site.
url: https://git.abdu.io

# CSS: path to CSS folder
css-folder: assets/css

# Media: path to folder containing all media (including projects)
media-folder: assets/media

#
# Global variables
#

# Logo: text with typewriter animation
logo: /abdullah

# Name: website's name
name: Abdullah Ibne Atiq

# Description: A brief description that appears under the logo
description: Computer Science student, with peculiar interest in XR technologies, actively engaging with Web Development and programming.

# Featured: an image displayed on social media when this website is linked, saved in the "media" folder
featured: siteFT.jpg

# Twitter: Twitter handle (without @)
twitter: abdullahibneat

# LinkedIn: link to LinkedIn profile
linkedin: abdullahibneat

# Email: email address
email: hello@abdu.io

# Skills: array of skills to be shown under the description
skills: [3D Modelling, Texturing, Animation, Video Editing, AR/VR, Unreal Engine, Unity, Front-end]

#
# Required plugins
#

plugins:
  - jekyll-sitemap  # Generates sitemap
  - jekyll-paginate # Paginates posts in index.html
  - jekyll-redirect-from # Redirection

# Customize posts URL format
permalink: /project/:title/

# How many posts per page in index.html?
paginate: 6

# Customize index pages URL format
paginate_path: "/page/:num/"
